// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-scheduled-meetings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_scheduled_meetings_default = defineTool({
  name: "list_scheduled_meetings",
  title: "List scheduled meetings",
  description: "List the signed-in user's scheduled LiveDesk meetings, ordered by date.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max meetings to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("scheduled_meetings").select("id, title, meeting_code, meeting_date, meeting_time, duration, recurrence, invitees, created_at").order("meeting_date", { ascending: true }).order("meeting_time", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { meetings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-scheduled-meeting.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function generateMeetingCode() {
  return (() => {
    const a = "abcdefghijkmnpqrstuvwxyz23456789";
    const b = crypto.getRandomValues(new Uint8Array(12));
    const s = Array.from(b, (x) => a[x % 32]).join("");
    return `${s.slice(0, 4)}-${s.slice(4, 8)}-${s.slice(8, 12)}`;
  })();
}
var create_scheduled_meeting_default = defineTool2({
  name: "create_scheduled_meeting",
  title: "Schedule a meeting",
  description: "Create a new scheduled LiveDesk meeting for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Meeting title."),
    meeting_date: z2.string().describe("Meeting date in YYYY-MM-DD format."),
    meeting_time: z2.string().describe("Meeting time in HH:MM (24h) format."),
    duration: z2.string().optional().describe("Duration label, e.g. '30 min', '1 hour'."),
    recurrence: z2.string().optional().describe("Recurrence rule label, e.g. 'weekly'."),
    invitees: z2.array(z2.string()).optional().describe("Invitee emails.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("scheduled_meetings").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      meeting_code: generateMeetingCode(),
      meeting_date: input.meeting_date,
      meeting_time: input.meeting_time,
      duration: input.duration ?? "30 min",
      recurrence: input.recurrence ?? null,
      invitees: input.invitees ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Scheduled meeting created with code ${data.meeting_code}.` }],
      structuredContent: { meeting: data }
    };
  }
});

// src/lib/mcp/tools/list-active-meetings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_active_meetings_default = defineTool3({
  name: "list_active_meeting_participants",
  title: "List active meeting participants",
  description: "List participants currently present in a LiveDesk meeting by meeting code.",
  inputSchema: {
    meeting_code: z3.string().trim().min(1).describe("The meeting code to inspect.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ meeting_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("meeting_presence").select("display_name, is_mic_on, is_camera_on, joined_at, updated_at").eq("meeting_code", meeting_code).order("joined_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { participants: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "e2e";
var mcp_default = defineMcp({
  name: "zoom-connect-mcp",
  title: "LiveDesk",
  version: "0.1.0",
  instructions: "Tools for LiveDesk. Use `list_scheduled_meetings` to see the signed-in user's upcoming meetings, `create_scheduled_meeting` to schedule one, and `list_active_meeting_participants` to see who is currently in a meeting.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_scheduled_meetings_default, create_scheduled_meeting_default, list_active_meetings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
